fresh-trash-project/fresh-trash-backend

database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/FreshTrashBackendApplication.java, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/entity/Address.java, src/main/java/freshtrash/freshtrashbackend/entity/Member.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/AccountStatus.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/LoginType.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/UserRole.java, src/main/java/freshtrash/freshtrashbackend/repository/MemberRepository.java
1주차 스프린트 계획에 따라, 가람님과 함께 회원가입 및 회원탈퇴 기능을 분담했습니다. 이에 따라, 두 기능에서 공통적으로 사용되는 Member 엔티티와 Repository를 먼저 추가했습니다.
ERD를 기준으로 members 테이블에 해당하는 Member 엔티티의 필드를 추가했으며, `Address`필드는 `@Embeddable`어노테이션을 활용해 별도의 클래스로 분리했습니다. 또한, 코드의 가독성과 유지관리를 용이하게 하기 위해 constants 패키지 내에 enum 타입으로 정의된 `loginType`, `userRole`, `accountStatus` 필드를 별도의 상수 클래스로 분리했습니다.
Member 엔티티에서 `@Table(name="member")`에서 `@Table(name="members")`로 변경
Closed: #2
=> Member 엔티티 및 Repository 추가

.gitignore, build.gradle, src/main/java/freshtrash/freshtrashbackend/FreshTrashBackendApplication.java, src/main/java/freshtrash/freshtrashbackend/dto/properties/LocalFileProperties.java, src/main/java/freshtrash/freshtrashbackend/dto/request/WasteRequest.java, src/main/java/freshtrash/freshtrashbackend/dto/response/ExceptionResponse.java, src/main/java/freshtrash/freshtrashbackend/dto/response/FieldErrorInfo.java, src/main/java/freshtrash/freshtrashbackend/entity/Address.java, src/main/java/freshtrash/freshtrashbackend/exception/GlobalExceptionHandler.java, src/main/java/freshtrash/freshtrashbackend/exception/WasteException.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/service/FileServiceInterface.java, src/main/java/freshtrash/freshtrashbackend/service/impl/LocalFileService.java, src/main/java/freshtrash/freshtrashbackend/service/impl/WasteService.java, src/main/resources/application-file.yml, src/main/resources/application.yml, src/test/java/freshtrash/freshtrashbackend/Fixture/Fixture.java, src/test/java/freshtrash/freshtrashbackend/Fixture/FixtureDto.java, src/test/java/freshtrash/freshtrashbackend/controller/WasteApiTest.java
- 폐기물, 경매, 프로필 이미지를 저장하기위한 서비스 로직을 구현합니다.
- 파일을 저장, 삭제하는 로직을 구현했습니다.
- 비용 문제를 고려하여 개발 환경에서는 로컬 경로에 파일을 저장하도록 반영했습니다.
- 파일 경로는 각 로컬 환경에서 프로젝트 디렉토리의 resources/imgs 를 기준으로 설정하였습니다. (e.g. /Users/joo/Desktop/fresh-trash-backend/src/main/resources/imgs)
- 테스트 코드 작성
- 기존 폐기물 등록 비지니스 로직에서 파라미터명이 modelFile으로 되어있어 imgFile로 수정
- 파일 저장 경로 설정을 위해 application-file.yml 추가
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 이내에 진행해 주세요.
- Closed: #7
=> 파일 저장 서비스 로직 구현

build.gradle, database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/dto/UserInfo.java, src/main/java/freshtrash/freshtrashbackend/dto/WasteDto.java, src/main/java/freshtrash/freshtrashbackend/dto/request/WasteRequest.java, src/main/java/freshtrash/freshtrashbackend/dto/security/MemberPrincipal.java, src/main/java/freshtrash/freshtrashbackend/entity/Member.java, src/main/java/freshtrash/freshtrashbackend/entity/Waste.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteRepository.java, src/main/java/freshtrash/freshtrashbackend/service/WasteService.java, src/test/java/freshtrash/freshtrashbackend/Fixture/Fixture.java, src/test/java/freshtrash/freshtrashbackend/Fixture/FixtureDto.java, src/test/java/freshtrash/freshtrashbackend/config/TestSecurityConfig.java, src/test/java/freshtrash/freshtrashbackend/controller/WasteApiTest.java
- Member는 여러 Waste를 가질 수 있으므로 Member와 Waste는 1:N 관계로 설정합니다. 또한 Waste의 수정/삭제는 작성자 또는 관리자만 가능하도록 방어 로직을 추가합니다.
- Member와 Waste의 연관 관계(1:N) 설정했습니다.
- Waste 등록/수정 시 반환되는 DTO 객체에 유저 정보(닉네임, 평점, 프로필 이미지 파일명, 주소)를 추가했습니다.
- MemberPrincipal에도 유저 정보(닉네임, 평점, 프로필 이미지 파일명, 주소)를 추가했습니다.
- Waste 수정/삭제 시 작성자 또는 관리자만 가능하도록 방어 로직을 추가했습니다.
- 유저 정보 추가에 따른 테스트 코드 수정
- spring security의 TestImplementation을 추가했습니다.
- Closed: #26
=> Member와 Waste의 연관 관계 설정 및 방어 로직 추가

build.gradle, src/main/java/freshtrash/freshtrashbackend/controller/SignInApi.java, src/main/java/freshtrash/freshtrashbackend/dto/properties/JwtProperties.java, src/main/java/freshtrash/freshtrashbackend/dto/request/LoginRequest.java, src/main/java/freshtrash/freshtrashbackend/dto/response/LoginResponse.java, src/main/java/freshtrash/freshtrashbackend/dto/security/MemberPrincipal.java, src/main/java/freshtrash/freshtrashbackend/exception/AuthException.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/security/Http401UnauthorizedAuthenticationEntryPoint.java, src/main/java/freshtrash/freshtrashbackend/security/JwtTokenFilter.java, src/main/java/freshtrash/freshtrashbackend/security/SecurityConfig.java, src/main/java/freshtrash/freshtrashbackend/security/TokenInfo.java, src/main/java/freshtrash/freshtrashbackend/security/TokenProvider.java, src/main/java/freshtrash/freshtrashbackend/service/SigInService.java, src/main/resources/application-security.yml, src/main/resources/application.yml, src/test/java/freshtrash/freshtrashbackend/config/TestSecurityConfig.java
- 유저가 로그인을 하면 jwt 토큰을 발급하여 프론트로 전달하도록 합니다. jwt 토큰에는 "id, role, nickname, rating, profile image filename, address" 정보를 포함하도록 합니다.
- JWT 토큰 인증을 위한 Security 설정
- session policy를 stateless 로 변경했습니다.
- 토큰 인증을 수행하는 JwtTokenFilter를 추가했습니다.
- 토큰 발급/파싱을 수행하는 클래스를 정의했습니다.
- 토큰 발급 메소드
- 토큰 파싱 (유효성 검사도 같이 수행합니다) 메소드
- 토큰 파싱 후 MemberPrincipal로 반환 메소드
- MemberPrincipal에 평점, 파일명(프로필 이미지), 주소 정보를 추가했습니다.
- 로그인 API 구현
- 로그인 성공 후 accessToken을 발급하고 반환합니다.
- 비밀번호 일치 여부도 확인합니다.
- Jwt 토큰의 secret key, expired time 값을 application-security.yml에 추가하고 변수로 처리했습니다.
- 변수 값들은 노션의 env 페이지에 추가했습니다.
- 테스트 Security 설정 수정
- test profile에 security profile을 …
=> AccessToken 인증 구현

build.gradle, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/dto/security/MemberPrincipal.java, src/main/java/freshtrash/freshtrashbackend/dto/security/OAuthAttributes.java, src/main/java/freshtrash/freshtrashbackend/security/CustomOAuth2SuccessHandler.java, src/main/java/freshtrash/freshtrashbackend/security/SecurityConfig.java, src/main/resources/application-security.yml
- Email/Password 입력으로 로그인할 수 있을 뿐만 아니라 네이버, 구글, 카카오 계정으로 로그인할 수 있도록 OAuth 기능을 구현합니다.
- `spring-boot-starter-oauth2-client` dependency 추가
- `application-security.yml`에 구글, 네이버, 카카오의 client-id, client-secret 등 OAuth 로그인 기능을 구현하는데 필요한 속성 값들을 추가했습니다.
- 값은 노션의 env 페이지에 추가했습니다.
- `MemberPrincipal`를 OAuth2User도 implements하여 OAuth2 로그인 후 반환되고 SecurityContextHolder에 저장될 객체로 사용합니다.
- SecurityConfig 수정
- OAuth2UserService 구현 및 빈 등록
- resource server로 부터 받은 userinfo를 통해 MemberPrincipal(OAuth2User)을 생성하여 반환합니다.
- 회원가입되지 않은 계정이라면 "ANONYMOUS" 권한으로 생성하여 서비스를 이용할 수 없도록 합니다. 이후 프론트와 협의하여 회원가입 페이지로 redirect 하는 등 추가 작업을 할 예정입니다.
- successHandler를 추가 정의하여 OAuth2 …
=> OAuth 로그인 기능 구현

database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/controller/AlarmApi.java, src/main/java/freshtrash/freshtrashbackend/entity/Alarm.java, src/main/java/freshtrash/freshtrashbackend/entity/AlarmArgs.java, src/main/java/freshtrash/freshtrashbackend/entity/Member.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/AlarmType.java, src/main/java/freshtrash/freshtrashbackend/exception/AlarmException.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/AlarmRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/EmitterRepository.java, src/main/java/freshtrash/freshtrashbackend/service/AlarmService.java
- 알람을 전송하기 전 SSE 연결을 요청하기 위한 API을 구현합니다.
- SSE 연결 요청 API 추가 구현했습니다
- SseEmitter를 저장/관리하기위한 EmitterRepository를 추가했습니다
- Thread-safe한 ConcurrentHashMap 자료구조를 사용했습니다
- key에는 임의로 "Emitter:Id:" + memberId로 지정합니다.
- SSE 연결을 위한 로직을 구현했습니다
- 임의로 timeout은 30분으로 지정하고 completion, timeout event 발생시 emitter를 삭제하도록 했습니다
- 첫 SSE 연결 후 임의로 데이터를 전송하여 `503` 에러를 예방합니다
- API 테스트는 Postman에서 수행했습니다. (Insomnia에서는 안되네요;;)
- 없음
- Closed: #46
=> 알람 SSE 연결 요청 API 구현

database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/dto/constants/LikeStatus.java, src/main/java/freshtrash/freshtrashbackend/entity/WasteLike.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/LikeStatus.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteLikeRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteRepository.java, src/main/java/freshtrash/freshtrashbackend/service/WasteService.java
- 관심 추가 삭제 기능 구현
- 본인폐기물에는 관심 추가 안됨 
- LikeStatus상태(LIKE, UNLIKE) 와 wasteLikes 테이블 데이터가 매치되어야함 
- 추가되었으면 폐기물 likeCount +1, 관심 삭제 되었으면 likeCount -1
- wasteRepository 에 likeCount update문 추가 
- update후 likeCount값을 가져와야하는데, 아직 해결못해서 현재는 변경된 row개수가 반환되고 있습니다. 추후 변경 예정 입니다.
- insert_data.sql 에 테스트를 위한 waste 데이터 추가, waste_likes 데이터 insert에 따른 waste like_count 수정
API test
- 관심 추가 
- abc@never.com 으로 로그인 후 token 값 넣음  
- RequestParam : likeStatus : LIKE 
- ResponseBody : 현재는 변경된 row수 반환 
- wasteLike에 추가된 데이터 
- 해당 waste 테이블 id=2 row의 like_count 1로 변경된것 확인 
- 관심 삭제 
- abc@never.com 으로 로그인 후 token 값 넣음  
- RequestParam : likeStatus : UNLIKE 
- …
=> 관심폐기물 추가 또는 삭제 기능 구현

src/main/java/freshtrash/freshtrashbackend/controller/AlarmApi.java, src/main/java/freshtrash/freshtrashbackend/dto/AlarmDto.java, src/main/java/freshtrash/freshtrashbackend/entity/AlarmArgs.java, src/main/java/freshtrash/freshtrashbackend/repository/AlarmRepository.java, src/main/java/freshtrash/freshtrashbackend/service/AlarmService.java
- 읽지 않은 모든 알람을 현재 로그인한 유저가 볼 수 있도록 전체 조회하는 API를 구현합니다.
- 알람 전체 조회 API 구현
- 임의로 페이징 처리를 적용했으며 이후 프론트와 협의를 통해 리스트로 변경될 수 있습니다.
- 알람 조회 쿼리 메소드 추가
- 현재 로그인한 유저의 ID와 읽지 않은 알람(readAt=null)만 조회합니다.
- AlarmArgs 수정
- `the given string value ... cannot be transformed to json object` 예외가 발생하여 `@NoArgsConstructor`를 적용하여 해결했습니다.
- API 테스트
- 없음
- Closed: #47
=> 알람 전체 조회 API 구현

database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/dto/constants/LikeStatus.java, src/main/java/freshtrash/freshtrashbackend/entity/WasteLike.java, src/main/java/freshtrash/freshtrashbackend/entity/constants/LikeStatus.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteLikeRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteRepository.java, src/main/java/freshtrash/freshtrashbackend/service/WasteService.java
폐기물 관심 추가 또는 삭제 하는 기능입니다.
- #30 
- #31 
- 두가지 PR리뷰받아 #24로 merge되었고, #24를 develop으로 merge하는 PR입니다.
- WasteLike entity 에서 Member, Waste테이블과 연관관계 설정
- WasteLikeRepository 생성
- create_table.sql 에 waste_likes 테이블 create문 추가 
- insert_data.sql 에 waste_likes insert문 추가, waste_likes에서 본인작성폐기물에 관심표시 안되므로 member insert문 추가 작성
- 관심 추가 또는 삭제 기능 구현(wasteService) : LikeStatue = LIKE 일때 wasteLikes에 관심추가된 데이터가 없으면 관심 추가 후 해당폐기물의 likecount 1개 증가, LikeStatue = UNLIKE 일때 wasteLikes에 관심추가된 데이터가 있으면 관심 삭제 후 해당 폐기물의 likecount 1개 감소 
- 이미 #30 #31 로 PR받은 사항이라 develop으로 충돌 안나도록 적용 하였습니다.
- 없음 
* Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, 코드 수정을 강제하지 …
=> 관심폐기물 추가 또는 삭제 

src/main/java/freshtrash/freshtrashbackend/dto/request/SignUpRequest.java, src/main/java/freshtrash/freshtrashbackend/entity/Member.java, src/test/java/freshtrash/freshtrashbackend/Fixture/Fixture.java
`Member` 엔티티에 빌더 패턴을 적용하고, 이에 따라 `SignUpRequest` DTO의 `toEntity` 메소드와 관련 테스트 코드를 수정합니다.
- `Member` 엔티티에 빌더 패턴 적용.
- `SignUpRequest` DTO의 `toEntity` 메소드에서 `Member` 엔티티 생성 시 빌더 패턴 사용으로 변경.
- `Member` 엔티티의 생성 과정을 테스트하는 코드를 빌더 패턴 사용으로 갱신.
없음
- Closed: #44
=> Member 엔티티에 빌더 패턴 적용 및 관련 DTO, 테스트 코드 수정

.gitignore, build.gradle, src/main/java/freshtrash/freshtrashbackend/config/JSONMetadataBuilderContributor.java, src/main/java/freshtrash/freshtrashbackend/config/JpaConfig.java, src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/entity/Waste.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/custom/CustomWasteRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/custom/CustomWasteRepositoryImpl.java, src/main/java/freshtrash/freshtrashbackend/service/WasteService.java, src/main/resources/application-common.yml, src/test/java/freshtrash/freshtrashbackend/config/TestSecurityConfig.java, src/test/java/freshtrash/freshtrashbackend/controller/WasteApiTest.java
- 폐기물 목록 페이지에서 제목, 주소(읍면동)으로 검색할 수 있도록 QueryDSL을 활용하여 구현합니다.
- QueryDSL Dependency 추가
- 폐기물 검색 쿼리
- 제목 검색: `?title={검색 키워드}`
- containsIgnoreCase를 적용
- 읍면동(주소) 검색: `?district={검색 키워드}`
- 검색 키워드와 일치해야함
- 주소 검색 쿼리
- 콘솔에서 직접 쿼리를 요청하게 될 경우 다음과 같습니다.
- `select * from wastes where JSON_CONTAINS(address, JSON_QUOTE('district'), '$.district');`
- JSON_CONTAINS, JSON_QUOTE 함수가 필요하게되어 이를 `MetadataBuilderContributor` 구현체에서 등록했습니다
- QueryDSL에서는 `booleanTemplate`을 사용하여 주소 검색 쿼리를 구현했습니다.
- hibernate sql log
- where 절만 확인해보면 다음과 같이 출력됩니다.
```
where
JSON_CONTAINS(waste0_.address, JSON_QUOTE(?), ?)=? 
or lower(waste0_.title) like ? escape '!' limit ?
```
- API …
=> 폐기물 제목, 주소(읍면동) 검색 기능 구현

database/initdb.d/create_table.sql, database/initdb.d/insert_data.sql, src/main/java/freshtrash/freshtrashbackend/entity/ChatMessage.java, src/main/java/freshtrash/freshtrashbackend/entity/ChatRoom.java, src/main/java/freshtrash/freshtrashbackend/repository/ChatMessageRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/ChatRoomRepository.java
채팅 기능에서 사용될 기본 엔티티와 레파지토리를 추가합니다. 
- `chat_message` 엔티티 설계
- `chat_room` 엔티티 설계
- `ChatMessageRepository` 인터페이스 추가
- `ChatRoomRepository` 인터페이스 추가
- DB 테이블의 생성 및 데이터 추가
- create_table.sql 파일에 chat_message, chat_room 테이블을 생성하기 위한 SQL문을 작성합니다.
- insert_data.sql 파일에 위에서 생성한 테이블에 데이터를 추가하기 위한 SQL문을 작성합니다.
- 도커를 사용하여 데이터베이스를 실행하는 컨테이너 안에서 터미널을 열어, 데이터가 성공적으로 추가되었는지 확인합니다.
없음
- Closed : #61
=> 채팅 기능을 위한 Entity 와 Repository 추가

build.gradle, src/main/java/freshtrash/freshtrashbackend/dto/properties/MailProperties.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/service/MailService.java, src/main/resources/application-mail.yml
- 인증코드 메일을 보내기전 메일이 유효한지 검증하는 기능입니다.
- 처음엔 mailgun api를 사용하려 살펴봤는데 무료버전으로는 임의 메일로 전송이 안되고, 등록해둔 메일로만 전송가능해서 [mail validation api](https://www.abstractapi.com/api/email-verification-validation-api) 를 사용하여 유효성을 검증하고, 메일 보내는 것은 기존 방법 그대로 두었습니다. 
- validation api의 반환값 중 이메일 전달 가능성을 나타내는 deliverability(DELIVERABLE, UNDELIVERABLE, UNKNOWN) 과 이메일의 도메인이 Abstract의 무료 이메일 제공업체에 등록되어있는지 여부인 is_free_email(true, false) 를 가지고 deliverability=DELIVERABLE 이면서 is_free_email=true 값일때 유효하다 판단합니다.
- api_key는 노션 .env파일에 적어뒀습니다
- jsonObject파싱을 위해 gradle에 gson을 추가했습니다.
- 인증메일 보내기전 isValidMail 수행 
- api test
인증코드 발송api에서 이메일 검증시 유효하지 않으면 위와 같이 예외처리됩니다.
- test case
- …
=> 메일 유효성 검증 기능 구현

src/main/java/freshtrash/freshtrashbackend/controller/AlarmApi.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/AlarmRepository.java, src/main/java/freshtrash/freshtrashbackend/service/AlarmService.java, src/test/java/freshtrash/freshtrashbackend/controller/AlarmApiTest.java, src/test/java/freshtrash/freshtrashbackend/service/AlarmServiceTest.java
- 프론트에서 알람을 클릭하면 해당 알람에 해당하는 대상 폐기물, 경매 등의 페이지로 이동하고 서버에서는 읽음 처리를 하도록 API를 구현합니다.
- 알람 읽음 처리 요청 API 구현
- 알람 읽음 처리 요청 시 로그인한 사용자가 대상 알람의 주인인지 확인합니다
- 대상 알람의 주인이 맞다면 알람의 readAt 속성 값을 읽은 일시로 update 합니다
- 알람 update readAt 쿼리 메소드
- 알람의 읽음 처리를 요청하는 사용자는 해당 알람의 주인 한 명 뿐이기 때문에 Transaction을 적용할 필요가 없다고 판단했습니다.
- Transaction이 필요없다고 판단하여 native query를 적용했습니다.
- 단위 테스트 코드 작성
- API 테스트
- 없음
- Closed: #71
=> 알람 읽음 처리 요청 API 구현

src/main/java/freshtrash/freshtrashbackend/controller/ChatApi.java, src/main/java/freshtrash/freshtrashbackend/dto/response/ChatMessageResponse.java, src/main/java/freshtrash/freshtrashbackend/dto/response/ChatRoomResponse.java, src/main/java/freshtrash/freshtrashbackend/dto/response/ChatRoomWithMessagesResponse.java, src/main/java/freshtrash/freshtrashbackend/entity/ChatRoom.java, src/main/java/freshtrash/freshtrashbackend/exception/ChatException.java, src/main/java/freshtrash/freshtrashbackend/exception/constants/ErrorCode.java, src/main/java/freshtrash/freshtrashbackend/repository/ChatRoomRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/MemberRepository.java, src/main/java/freshtrash/freshtrashbackend/service/ChatService.java, src/test/java/freshtrash/freshtrashbackend/Fixture/Fixture.java, src/test/java/freshtrash/freshtrashbackend/controller/ChatApiTest.java, src/test/java/freshtrash/freshtrashbackend/service/ChatServiceTest.java
- 채팅방 목록과 채팅방 단일 + 메시지를 조회하는 API를 구현합니다.
- ChatRoom과 ChatMessage의 oneToMany 연관관계 설정
- 채팅방 조회 API 구현
- 로그인 사용자의 모든 채팅방을 조회
- 채팅방 단일 + 모든 메시지 조회
- 요청 시 조회하려는 채팅방에 대한 권한이 있는지 판단
- 채팅방 조회 단위 테스트 코드 작성
- API 테스트
- 채팅방 목록
- 채팅방 단일 + 모든 메시지
- chat_rooms의 open_or_close 속성 타입 수정
- tinyint -> bit로 수정
- Closed: #77
=> 채팅방 목록, 단일 조회 API 구현

src/main/java/freshtrash/freshtrashbackend/controller/WasteApi.java, src/main/java/freshtrash/freshtrashbackend/service/WasteService.java, src/test/java/freshtrash/freshtrashbackend/Fixture/FixtureDto.java, src/test/java/freshtrash/freshtrashbackend/controller/WasteApiTest.java, src/test/java/freshtrash/freshtrashbackend/service/WasteServiceTest.java
- Waste 수정 시 save -> upload 후 flush를 해도 파일 delete를 해도 Transaction에 의해 rollback되는 문제가 있습니다. 따라서 수정된 waste의 fileName이 변경되었는지를 판단하여 업로드 여부를 확인하고 이후 파일을 삭제하도록 수정합니다.
- Waste Update 로직에서 파일 삭제 코드를 분리
- Controller Layer에서 파일 수정 후 분리한 파일 삭제를 실행하도록 수정
- Waste Delete 시 파일 삭제 코드 분리
- DB 삭제와 파일 삭제는 반드시 같이 실행될 필요없으므로 Transaction을 삭제하고 파일 삭제 코드를 분리
- 테스트 코드 수정
- 없음
- Closed: #87
=> Waste Update 로직 수정 및 불필요한 Transaction 삭제/리팩토링

src/main/java/freshtrash/freshtrashbackend/config/RedisConfig.java, src/main/java/freshtrash/freshtrashbackend/dto/cache/EmailCodeCache.java, src/main/java/freshtrash/freshtrashbackend/dto/security/MemberPrincipal.java, src/main/java/freshtrash/freshtrashbackend/repository/MemberCacheRepository.java, src/main/java/freshtrash/freshtrashbackend/security/CustomOAuth2SuccessHandler.java, src/main/java/freshtrash/freshtrashbackend/security/JwtTokenFilter.java, src/main/java/freshtrash/freshtrashbackend/security/SecurityConfig.java, src/main/java/freshtrash/freshtrashbackend/security/TokenProvider.java, src/main/java/freshtrash/freshtrashbackend/service/MailService.java, src/main/java/freshtrash/freshtrashbackend/service/MemberService.java, src/test/java/freshtrash/freshtrashbackend/config/TestSecurityConfig.java
- 클라이언트에 전달되는 토큰에 유저 정보들이 담겨있습니다. 이때 토큰에 담긴 유저 정보들이 클라이언트에 저장되면 보안적인면에서 취약할 수 있고 토큰에 담긴 정보들이 적지않기 때문에 요청할 때 비용이 발생합니다. 따라서 토큰에는 유저의 Id 정도만 담아두고 유저 정보를 Redis에 캐싱하여 가져와 사용하도록 기능을 구현합니다.
- RedisConfig 수정
- 사용하지 않는 RedisTemplate 빈 삭제
- 유저 정보 캐싱
- 로그인 후 member id를 토큰의 payload에 담아 발급하고 redis에 MemberPrincipal을 캐싱
- API 요청 시 토큰을 받고 토큰에 담긴 id로 캐싱한 유저 정보 조회
- 캐싱 여부 확인
- EmailCode의 TTL 설정을 `@RedisHash`에 설정
- Closed: #83
=> Redis를 사용한 유저 정보 캐싱

src/main/java/freshtrash/freshtrashbackend/controller/MemberApi.java, src/main/java/freshtrash/freshtrashbackend/dto/request/SignUpRequest.java
- 초기 회원가입된 유저의 경우 프로필 이미지 파일이 null 값을 가지고 있는데, 현재 유저정보수정 기능에서 기존 이미지파일 null체크가 없어서 기존파일 삭제 전 null값 조건을 추가하려 합니다 
- 회원가입시 비밀번호 유효성 추가 
- 유저정보수정에서 이전파일 삭제전 StringUtils.hasText(oldFile) 조건 추가 
- SignUpRequest에 @Pattern 추가 (비밀번호는 영문자와 숫자, 특수기호가 적어도 1개 이상 포함)
- 없음 
- Closed : #97
=> 유저정보 수정에서 기존파일 null 체크 & 회원가입 비밀번호 유효성 체크 

src/main/java/freshtrash/freshtrashbackend/repository/EmitterRepository.java, src/main/java/freshtrash/freshtrashbackend/service/AlarmService.java
- MPA(Multi-Page Application)에서 페이지 이동 시마다 새로운 SseEmitter를 생성합니다. 그리고 이전에 생성한 SseEmitter는 그대로 남게됩니다. 따라서 페이지 이동 시 Sse 연결을 시도할 때 이전에 생성한 SseEmitter가 있는지 확인 후 없을 경우에만 생성하도록 합니다.
- SSE 연결 시도할 때 이전에 생성한 SseEmitter가 존재하는지 확인합니다.
- 이전에 생성한 SseEmitter가 없을 경우에만 새로 생성합니다.
- 없음
- Closed: #100
=> SSE 연결 시도할 때 이전에 생성한 SseEmitter가 존재하는지 확인

src/main/java/freshtrash/freshtrashbackend/dto/constants/TransactionMemberType.java, src/main/java/freshtrash/freshtrashbackend/repository/WasteRepository.java, src/main/java/freshtrash/freshtrashbackend/service/TransactionService.java
- 프론트의 요구사항에 따라 판매자가 판매 폐기물을 조회하려고 할 때 Close, Booking, Ongoing인 상태 모두 반환하도록 합니다. 이때 Close인 상태의 폐기물, Close가 아닌 폐기물을 구분해야합니다. 그러면 프론트에서 판매자가 판매 중(Close가 아닌)인 폐기물과 판매 완료(Close)한 폐기물을 구분하여 화면에 표시할 수 있습니다.
- memberType을 SELLER_ONGOING, SELLER_CLOSE로 구분
- SELLER_ONGOING: 판매 중 폐기물 조회
- SELLER_CLOSE: 판매 완료 폐기물 조회
- API 테스트
- 없음
- Closed: #104 104
=> 판매자가 판매 중인 폐기물과 판매한 폐기물을 구분하여 조회

src/main/java/freshtrash/freshtrashbackend/config/WebSocketConfig.java, src/main/java/freshtrash/freshtrashbackend/controller/ChatApi.java, src/main/java/freshtrash/freshtrashbackend/controller/ChatMessageApi.java, src/main/java/freshtrash/freshtrashbackend/dto/request/ChatMessageRequest.java, src/main/java/freshtrash/freshtrashbackend/service/ChatMessageService.java, src/main/java/freshtrash/freshtrashbackend/service/ChatService.java, src/main/resources/static/chat_stomp.js, src/main/resources/static/index.html
- 채팅방에서 판매자/구매자 간의 메시지 전송을 위해 웹소켓 stomp를 사용한 pub/sub 기능을 구현합니다.
- websocket config 수정
- ws -> chat-ws 로 수정
- subscribe prefix를 topic -> chat으로 수정
- 웹소켓의 allowedOrigins를 * -> localhost:5173 으로 제한
- chatMessageApi 추가
- 서버 기준 subscribe: /{chatRoomId}/message/{memberId}
- 서버 기준 publish: /chat/{chatRoomId}/message
- DB에 메시지를 저장하고 클라이언트로 publish 합니다.
- 채팅 pub/sub 테스트
- 임의로 html/js를 추가하여 테스트를 수행했습니다.
- 없음
- Closed: #92
=> 채팅 pub/sub 구현

src/main/java/freshtrash/freshtrashbackend/security/CustomOAuth2SuccessHandler.java
- OAuth 인증 후 토큰을 클라이언트에게 넘겨줄 수 있도록 코드를 수정합니다. 또한 회원가입이 되지않았을 경우 이메일, 닉네임 정보와 함께 회원가입 페이지로 redirect할 수 있도록 적용합니다.
- 적용한 로직
- 회원가입이 되었을 경우 토큰과 함께 홈페이지로 redirect합니다.
- 회원가입이 안되었을 경우 사용자 정보와 함께 회원가입 페이지로 redirect 합니다.
- 쿠키 설정
- 클라이언트에 전달되는 쿠키 설정은 다음과 같습니다.
- maxAge: 10분
- path: /
- 추후 실제로 배포하게될 경우 수정될 수 있습니다.
- 없음
- Closed: #114
=> OAuth 인증 완료 후 토큰 전달 및 사용자 정보와 함께 redirect 적용

src/main/java/freshtrash/freshtrashbackend/controller/TransactionApi.java, src/main/java/freshtrash/freshtrashbackend/dto/constants/AlarmMessage.java, src/main/java/freshtrash/freshtrashbackend/repository/ChatRoomRepository.java, src/main/java/freshtrash/freshtrashbackend/repository/projections/BuyerIdSummary.java, src/main/java/freshtrash/freshtrashbackend/service/ChatRoomService.java, src/test/java/freshtrash/freshtrashbackend/controller/TransactionApiTest.java
- 채팅방에서 판매자가 예약중 선택시 : 폐기물, 채팅방 SellStatus가 Booking으로 수정되고 해당 채팅방 구매자에게 알림을 보냅니다.
- 채팅방에서 판매자가 판매중 선택시 : 폐기물, 채팅방 SellStatus가 Ongoing으로 수정되고 해당 폐기물에 채팅요청했던 구매자들에게 알림을 보냅니다.
- 기존에 예약중 기능으로 구현되어 있던 TransactionApi의 updateBooking을 updateSellStatus로 판매중도 함께 처리할 수 있도록 변경 
- @RequestParam SellStatus sellStatus 를 요청값에 넣었습니다.
- 공통 : 폐기물, 채팅방의 SellStatus를 요청값으로 받은 sellStatus로 update합니다.
- sellStatus = BOOKING 예약중인 경우 : 해당 채팅방의 구매자에게 예약중 알림을 보냅니다.
- sellStatus = ONGOING 판매중인 경우 : 해당 폐기물에 채팅요청했던 다른 구매자들에게 판매중 알림을 보냅니다. (현재 채팅방 구매자는 제외)
- 채팅요청했던 다른 구매자들 조회해올때 BuyerIdSummary 생성하여 projection적용하였습니다.
- 테스트 코드 수정
- …
=> 채팅방에서 판매상태 변경(예약중, 판매중) 기능 

.github/workflows/deploy.yaml, appspec.yml, database/mariadb/initdb.d/insert_data.sql, deploy_scripts/deploy_script.sh, src/main/java/freshtrash/freshtrashbackend/config/AsyncConfig.java, src/main/java/freshtrash/freshtrashbackend/config/RabbitMQConfig.java, src/main/java/freshtrash/freshtrashbackend/config/constants/QueueType.java, src/main/java/freshtrash/freshtrashbackend/controller/TransactionApi.java, src/main/java/freshtrash/freshtrashbackend/dto/events/AlarmEvent.java, src/main/java/freshtrash/freshtrashbackend/dto/events/BaseEvent.java, src/main/java/freshtrash/freshtrashbackend/dto/response/AlarmResponse.java, src/main/java/freshtrash/freshtrashbackend/entity/Alarm.java, src/main/java/freshtrash/freshtrashbackend/service/AlarmService.java, src/main/java/freshtrash/freshtrashbackend/service/EventService.java, src/main/java/freshtrash/freshtrashbackend/service/RabbitMqProducer.java, src/main/resources/application-amqp.yml, src/main/resources/application.yml
- 폐기물 거래 완료, 상태 변경, 신고하기에 대한 MQ를 나누어서 분산 처리를 적용합니다. 또한 ApplicationEventPublisher를 사용하여 Event 객체를 비동기적으로 처리함으로써 효율성을 향상시키도록 합니다.
추가로 message publish 중 예외가 발생했을시 re-deliver가 되도록 SimpleRetryPolicy를 적용합니다.
- AMQP의 SimpleRetryPolicy 적용
- max-attempts를 3으로 설정하여 1초 간격으로 3회 재실행하도록 설정
- SimpleRetryPolicy를 적용하지 않을 경우 예외가 발생했을 때 무한정 재실행하게됩니다.
- RabbitMQ 설정 변경
- 거래완료, 상태변경, 신고하기에 대한 MQ를 분리하고 MessageConverter를 Jackson2JsonMessageConverter로 지정
- MessageConverter를 따로 지정하지 않을 경우 byte array 형식으로 convert 됩니다.
- `ApplicationEventPublisher` 적용
- Event(`AlarmEvent`) 객체를 정의하여 거래완료, 상태변경, 신고하기 로직이 수행될 때 ApplicationEventPublisher를 통해 처리되도 록 적용했습니다.
- EventListener에 비동기 처리를 적용했습니다.
- 전체 구조
- insert_data.sql의 알람 데이터에서 alarm_args에 들어있는 id 타입 변경
- Excuter 빈 이름이 잘못되어 수정(getTaskExecutor -> …
=> 알람 전송 기능에 적용한 RabbitMQ의 큐와 구조 변경

build.gradle, docker-compose-local.yml, rabbitmq/Dockerfile, src/main/java/freshtrash/freshtrashbackend/config/RabbitMQConfig.java, src/main/java/freshtrash/freshtrashbackend/config/WebSocketConfig.java, src/main/java/freshtrash/freshtrashbackend/config/constants/QueueType.java, src/main/java/freshtrash/freshtrashbackend/controller/ChatMessageApi.java, src/main/resources/application-amqp.yml, src/main/resources/application.yml, src/main/resources/static/chat/chat_stomp.js
- StompBroker가 기존에 SimpleBroker로 지정되어있어 Application이 실행되는 서버에 종속적이다는 단점이 있습니다. scale-out 시 서버 간의 메시지 공유가 안되고 메시지 처리 역할을 RabbitMQ에 넘기면서 서버의 부담을 덜 수 있길 기대합니다.
- WebSocket에 외부 브로커 RabbitMQ 적용
- RabbitMQ 설정 변경
- `amq.topic`이름을 가지는 topicExchange 추가
- `chat-queue` 이름을 가지는 queue 추가
- 추가한 queue와 exchange는 `chats.#` routing key로 바인딩
- WebSocket 설정 변경
- 외부 브로커 설정
- destinationPrefix는 `/topic`으로 변경
- 웹소켓의 외부 브로커 사용을 위해 reactor-netty dependency 추가
- rabbitMq의 도커 설정 수정
- 15672, 61613 포트 추가
- 15672 포트는 브라우저에서 접근하여 설정 변경/모니터링 등을 할 수 있도록 추가했습니다.
- localhost:51672 로 접속해서 rabbitmq.username/rabbitmq.password로 로그인
- 61613 포트는 rabbitMq stomp 사용을 위해 추가했습니다. 
- 추가된 환경 변수들은 노션에 추가했습니다.
* Review는 특수한 케이스가 …
=> WebsocketStompBroker를 외부 브로커(RabbitMQ)로 적용
